package practical.session;
import java.math.BigInteger;

import practical.session.Models.*;




/*
 * This source file was generated by the Gradle 'init' task
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BigInteger bigNumber = BigInteger.ONE;

        System.out.println("Recursive: " + FactorialAlgorithm.factorialRecursive(10));

        System.out.println("Iterative: " + FactorialAlgorithm.factorialIterative(10));
    }
}
